namespace MandraSoft.PokemonGo.DAL.Migrations
{
    using Models.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<MandraSoft.PokemonGo.DAL.PokemonDb>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(MandraSoft.PokemonGo.DAL.PokemonDb context)
        {
            context.Pokemons.AddOrUpdate(x => x.Id,
                new Pokemon { Id = 1, LabelEn = "Bulbasaur", LabelFr = "Bulbizarre", LabelDe = "Bisasam" },
                new Pokemon { Id = 2, LabelEn = "Ivysaur", LabelFr = "Herbizarre", LabelDe = "Bisaknosp" },
                new Pokemon { Id = 3, LabelEn = "Venusaur", LabelFr = "Florizarre", LabelDe = "Bisaflor" },
                new Pokemon { Id = 4, LabelEn = "Charmander", LabelFr = "Salamèche", LabelDe = "Glumanda" },
                new Pokemon { Id = 5, LabelEn = "Charmeleon", LabelFr = "Reptincel", LabelDe = "Glutexo" },
                new Pokemon { Id = 6, LabelEn = "Charizard", LabelFr = "Dracaufeu", LabelDe = "Glurak" },
                new Pokemon { Id = 7, LabelEn = "Squirtle", LabelFr = "Carapuce", LabelDe = "Schiggy" },
                new Pokemon { Id = 8, LabelEn = "Wartortle", LabelFr = "Carabaffe", LabelDe = "Schillok" },
                new Pokemon { Id = 9, LabelEn = "Blastoise", LabelFr = "Tortank", LabelDe = "Turtok" },
                new Pokemon { Id = 10, LabelEn = "Caterpie", LabelFr = "Chenipan", LabelDe = "Raupy" },
                new Pokemon { Id = 11, LabelEn = "Metapod", LabelFr = "Chrysacier", LabelDe = "Safcon" },
                new Pokemon { Id = 12, LabelEn = "Butterfree", LabelFr = "Papilusion", LabelDe = "Smettbo" },
                new Pokemon { Id = 13, LabelEn = "Weedle", LabelFr = "Aspicot", LabelDe = "Hornliu" },
                new Pokemon { Id = 14, LabelEn = "Kakuna", LabelFr = "Coconfort", LabelDe = "Kokuna" },
                new Pokemon { Id = 15, LabelEn = "Beedrill", LabelFr = "Dardargnan", LabelDe = "Bibor" },
                new Pokemon { Id = 16, LabelEn = "Pidgey", LabelFr = "Roucool", LabelDe = "Taubsi" },
                new Pokemon { Id = 17, LabelEn = "Pidgeotto", LabelFr = "Roucoups", LabelDe = "Tauboga" },
                new Pokemon { Id = 18, LabelEn = "Pidgeot", LabelFr = "Roucarnage", LabelDe = "Tauboss" },
                new Pokemon { Id = 19, LabelEn = "Rattata", LabelFr = "Rattata", LabelDe = "Rattfratz" },
                new Pokemon { Id = 20, LabelEn = "Raticate", LabelFr = "Rattatac", LabelDe = "Rattikarl" },
                new Pokemon { Id = 21, LabelEn = "Spearow", LabelFr = "Piafabec", LabelDe = "Habitak" },
                new Pokemon { Id = 22, LabelEn = "Fearow", LabelFr = "Rapasdepic", LabelDe = "Ibitak" },
                new Pokemon { Id = 23, LabelEn = "Ekans", LabelFr = "Abo", LabelDe = "Rettan" },
                new Pokemon { Id = 24, LabelEn = "Arbok", LabelFr = "Arbok", LabelDe = "Arbok" },
                new Pokemon { Id = 25, LabelEn = "Pikachu", LabelFr = "Pikachu", LabelDe = "Pikachu" },
                new Pokemon { Id = 26, LabelEn = "Raichu", LabelFr = "Raichu", LabelDe = "Raichu" },
                new Pokemon { Id = 27, LabelEn = "Sandshrew", LabelFr = "Sabelette", LabelDe = "Sandan" },
                new Pokemon { Id = 28, LabelEn = "Sandslash", LabelFr = "Sablaireau", LabelDe = "Sandamer" },
                new Pokemon { Id = 29, LabelEn = "Nidoran♀", LabelFr = "Nidoran♀", LabelDe = "Nidoran♀" },
                new Pokemon { Id = 30, LabelEn = "Nidorina", LabelFr = "Nidorina", LabelDe = "Nidorina" },
                new Pokemon { Id = 31, LabelEn = "Nidoqueen", LabelFr = "Nidoqueen", LabelDe = "Nidoqueen" },
                new Pokemon { Id = 32, LabelEn = "Nidoran♂", LabelFr = "Nidoran♂", LabelDe = "Nidoran♂" },
                new Pokemon { Id = 33, LabelEn = "Nidorino", LabelFr = "Nidorino", LabelDe = "Nidorino" },
                new Pokemon { Id = 34, LabelEn = "Nidoking", LabelFr = "Nidoking", LabelDe = "Nidoking" },
                new Pokemon { Id = 35, LabelEn = "Clefairy", LabelFr = "Mélofée", LabelDe = "Piepi" },
                new Pokemon { Id = 36, LabelEn = "Clefable", LabelFr = "Mélodelfe", LabelDe = "Pixi" },
                new Pokemon { Id = 37, LabelEn = "Vulpix", LabelFr = "Goupix", LabelDe = "Vulpix" },
                new Pokemon { Id = 38, LabelEn = "Ninetales", LabelFr = "Feunard", LabelDe = "Vulnona" },
                new Pokemon { Id = 39, LabelEn = "Jigglypuff", LabelFr = "Rondoudou", LabelDe = "Pummeluff" },
                new Pokemon { Id = 40, LabelEn = "Wigglytuff", LabelFr = "Grodoudou", LabelDe = "Knuddeluff" },
                new Pokemon { Id = 41, LabelEn = "Zubat", LabelFr = "Nosferapti", LabelDe = "Zubat" },
                new Pokemon { Id = 42, LabelEn = "Golbat", LabelFr = "Nosferalto", LabelDe = "Golbat" },
                new Pokemon { Id = 43, LabelEn = "Oddish", LabelFr = "Mystherbe", LabelDe = "Myrapla" },
                new Pokemon { Id = 44, LabelEn = "Gloom", LabelFr = "Ortide", LabelDe = "Duflor" },
                new Pokemon { Id = 45, LabelEn = "Vileplume", LabelFr = "Rafflesia", LabelDe = "Giflor" },
                new Pokemon { Id = 46, LabelEn = "Paras", LabelFr = "Paras", LabelDe = "Paras" },
                new Pokemon { Id = 47, LabelEn = "Parasect", LabelFr = "Parasect", LabelDe = "Parasek" },
                new Pokemon { Id = 48, LabelEn = "Venonat", LabelFr = "Mimitoss", LabelDe = "Bluzuk" },
                new Pokemon { Id = 49, LabelEn = "Venomoth", LabelFr = "Aéromite", LabelDe = "Omot" },
                new Pokemon { Id = 50, LabelEn = "Diglett", LabelFr = "Taupiqueur", LabelDe = "Digda" },
                new Pokemon { Id = 51, LabelEn = "Dugtrio", LabelFr = "Triopikeur", LabelDe = "Digdri" },
                new Pokemon { Id = 52, LabelEn = "Meowth", LabelFr = "Miaouss", LabelDe = "Mauzi" },
                new Pokemon { Id = 53, LabelEn = "Persian", LabelFr = "Persian", LabelDe = "Snobilikat" },
                new Pokemon { Id = 54, LabelEn = "Psyduck", LabelFr = "Psykokwak", LabelDe = "Enton" },
                new Pokemon { Id = 55, LabelEn = "Golduck", LabelFr = "Akwakwak", LabelDe = "Entoron" },
                new Pokemon { Id = 56, LabelEn = "Mankey", LabelFr = "Férosinge", LabelDe = "Menki" },
                new Pokemon { Id = 57, LabelEn = "Primeape", LabelFr = "Colossinge", LabelDe = "Rasaff" },
                new Pokemon { Id = 58, LabelEn = "Growlithe", LabelFr = "Caninos", LabelDe = "Fukano" },
                new Pokemon { Id = 59, LabelEn = "Arcanine", LabelFr = "Arcanin", LabelDe = "Arkani" },
                new Pokemon { Id = 60, LabelEn = "Poliwag", LabelFr = "Ptitard", LabelDe = "Quapsel" },
                new Pokemon { Id = 61, LabelEn = "Poliwhirl", LabelFr = "Têtarte", LabelDe = "Quaputzi" },
                new Pokemon { Id = 62, LabelEn = "Poliwrath", LabelFr = "Tartard", LabelDe = "Quappo" },
                new Pokemon { Id = 63, LabelEn = "Abra", LabelFr = "Abra", LabelDe = "Abra" },
                new Pokemon { Id = 64, LabelEn = "Kadabra", LabelFr = "Kadabra", LabelDe = "Kadabra" },
                new Pokemon { Id = 65, LabelEn = "Alakazam", LabelFr = "Alakazam", LabelDe = "Simsala" },
                new Pokemon { Id = 66, LabelEn = "Machop", LabelFr = "Machoc", LabelDe = "Machollo" },
                new Pokemon { Id = 67, LabelEn = "Machoke", LabelFr = "Machopeur", LabelDe = "Maschock" },
                new Pokemon { Id = 68, LabelEn = "Machamp", LabelFr = "Mackogneur", LabelDe = "Machomei" },
                new Pokemon { Id = 69, LabelEn = "Bellsprout", LabelFr = "Chétiflor", LabelDe = "Knofensa" },
                new Pokemon { Id = 70, LabelEn = "Weepinbell", LabelFr = "Boustiflor", LabelDe = "Ultrigaria" },
                new Pokemon { Id = 71, LabelEn = "Victreebel", LabelFr = "Empiflor", LabelDe = "Sarzenia" },
                new Pokemon { Id = 72, LabelEn = "Tentacool", LabelFr = "Tentacool", LabelDe = "Tentacha" },
                new Pokemon { Id = 73, LabelEn = "Tentacruel", LabelFr = "Tentacruel", LabelDe = "Tentoxa" },
                new Pokemon { Id = 74, LabelEn = "Geodude", LabelFr = "Racaillou", LabelDe = "Kleinstein" },
                new Pokemon { Id = 75, LabelEn = "Graveler", LabelFr = "Gravalanch", LabelDe = "Georok" },
                new Pokemon { Id = 76, LabelEn = "Golem", LabelFr = "Grolem", LabelDe = "Geowaz" },
                new Pokemon { Id = 77, LabelEn = "Ponyta", LabelFr = "Ponyta", LabelDe = "Ponita" },
                new Pokemon { Id = 78, LabelEn = "Rapidash", LabelFr = "Galopa", LabelDe = "Gallopa" },
                new Pokemon { Id = 79, LabelEn = "Slowpoke", LabelFr = "Ramoloss", LabelDe = "Flegmon" },
                new Pokemon { Id = 80, LabelEn = "Slowbro", LabelFr = "Flagadoss", LabelDe = "Lahmus" },
                new Pokemon { Id = 81, LabelEn = "Magnemite", LabelFr = "Magnéti", LabelDe = "Magnetilo" },
                new Pokemon { Id = 82, LabelEn = "Magneton", LabelFr = "Magnéton", LabelDe = "Magneton" },
                new Pokemon { Id = 83, LabelEn = "Farfetch'd", LabelFr = "Canarticho", LabelDe = "Porenta" },
                new Pokemon { Id = 84, LabelEn = "Doduo", LabelFr = "Doduo", LabelDe = "Dodu" },
                new Pokemon { Id = 85, LabelEn = "Dodrio", LabelFr = "Dodrio", LabelDe = "Dodri" },
                new Pokemon { Id = 86, LabelEn = "Seel", LabelFr = "Otaria", LabelDe = "Jurob" },
                new Pokemon { Id = 87, LabelEn = "Dewgong", LabelFr = "Lamantine", LabelDe = "Jugong" },
                new Pokemon { Id = 88, LabelEn = "Grimer", LabelFr = "Tadmorv", LabelDe = "Sleima" },
                new Pokemon { Id = 89, LabelEn = "Muk", LabelFr = "Grotadmorv", LabelDe = "Sleimok" },
                new Pokemon { Id = 90, LabelEn = "Shellder", LabelFr = "Kokiyas", LabelDe = "Muschas" },
                new Pokemon { Id = 91, LabelEn = "Cloyster", LabelFr = "Crustabri", LabelDe = "Austos" },
                new Pokemon { Id = 92, LabelEn = "Gastly", LabelFr = "Fantominus", LabelDe = "Nebulak" },
                new Pokemon { Id = 93, LabelEn = "Haunter", LabelFr = "Spectrum", LabelDe = "Alpollo" },
                new Pokemon { Id = 94, LabelEn = "Gengar", LabelFr = "Ectoplasma", LabelDe = "Gengar" },
                new Pokemon { Id = 95, LabelEn = "Onix", LabelFr = "Onix", LabelDe = "Onix" },
                new Pokemon { Id = 96, LabelEn = "Drowzee", LabelFr = "Soporifik", LabelDe = "Traumato" },
                new Pokemon { Id = 97, LabelEn = "Hypno", LabelFr = "Hypnomade", LabelDe = "Hypno" },
                new Pokemon { Id = 98, LabelEn = "Krabby", LabelFr = "Krabby", LabelDe = "Krabby" },
                new Pokemon { Id = 99, LabelEn = "Kingler", LabelFr = "Krabboss", LabelDe = "Kingler" },
                new Pokemon { Id = 100, LabelEn = "Voltorb", LabelFr = "Voltorbe", LabelDe = "Voltobal" },
                new Pokemon { Id = 101, LabelEn = "Electrode", LabelFr = "Électrode", LabelDe = "Lektrobal" },
                new Pokemon { Id = 102, LabelEn = "Exeggcute", LabelFr = "Nœunœuf", LabelDe = "Owei" },
                new Pokemon { Id = 103, LabelEn = "Exeggutor", LabelFr = "Noadkoko", LabelDe = "Kokowei" },
                new Pokemon { Id = 104, LabelEn = "Cubone", LabelFr = "Osselait", LabelDe = "Tragosso" },
                new Pokemon { Id = 105, LabelEn = "Marowak", LabelFr = "Ossatueur", LabelDe = "Knogga" },
                new Pokemon { Id = 106, LabelEn = "Hitmonlee", LabelFr = "Kicklee", LabelDe = "Kicklee" },
                new Pokemon { Id = 107, LabelEn = "Hitmonchan", LabelFr = "Tygnon", LabelDe = "Nockchan" },
                new Pokemon { Id = 108, LabelEn = "Lickitung", LabelFr = "Excelangue", LabelDe = "Schlurp" },
                new Pokemon { Id = 109, LabelEn = "Koffing", LabelFr = "Smogo", LabelDe = "Smogon" },
                new Pokemon { Id = 110, LabelEn = "Weezing", LabelFr = "Smogogo", LabelDe = "Smogmog" },
                new Pokemon { Id = 111, LabelEn = "Rhyhorn", LabelFr = "Rhinocorne", LabelDe = "Rihorn" },
                new Pokemon { Id = 112, LabelEn = "Rhydon", LabelFr = "Rhinoféros", LabelDe = "Rizeros" },
                new Pokemon { Id = 113, LabelEn = "Chansey", LabelFr = "Leveinard", LabelDe = "Chaneira" },
                new Pokemon { Id = 114, LabelEn = "Tangela", LabelFr = "Saquedeneu", LabelDe = "Tangela" },
                new Pokemon { Id = 115, LabelEn = "Kangaskhan", LabelFr = "Kangourex", LabelDe = "Kangama" },
                new Pokemon { Id = 116, LabelEn = "Horsea", LabelFr = "Hypotrempe", LabelDe = "Seeper" },
                new Pokemon { Id = 117, LabelEn = "Seadra", LabelFr = "Hypocéan", LabelDe = "Seemon" },
                new Pokemon { Id = 118, LabelEn = "Goldeen", LabelFr = "Poissirène", LabelDe = "Goldini" },
                new Pokemon { Id = 119, LabelEn = "Seaking", LabelFr = "Poissoroy", LabelDe = "Golking" },
                new Pokemon { Id = 120, LabelEn = "Staryu", LabelFr = "Stari", LabelDe = "Sterndu" },
                new Pokemon { Id = 121, LabelEn = "Starmie", LabelFr = "Staross", LabelDe = "Starmie" },
                new Pokemon { Id = 122, LabelEn = "Mr. Mime", LabelFr = "M. Mime", LabelDe = "Pantimos" },
                new Pokemon { Id = 123, LabelEn = "Scyther", LabelFr = "Insécateur", LabelDe = "Sichlor" },
                new Pokemon { Id = 124, LabelEn = "Jynx", LabelFr = "Lippoutou", LabelDe = "Rossana" },
                new Pokemon { Id = 125, LabelEn = "Electabuzz", LabelFr = "Élektek", LabelDe = "Elektek" },
                new Pokemon { Id = 126, LabelEn = "Magmar", LabelFr = "Magmar", LabelDe = "Magmar" },
                new Pokemon { Id = 127, LabelEn = "Pinsir", LabelFr = "Scarabrute", LabelDe = "Pinsir" },
                new Pokemon { Id = 128, LabelEn = "Tauros", LabelFr = "Tauros", LabelDe = "Tauros" },
                new Pokemon { Id = 129, LabelEn = "Magikarp", LabelFr = "Magicarpe", LabelDe = "Karpador" },
                new Pokemon { Id = 130, LabelEn = "Gyarados", LabelFr = "Léviator", LabelDe = "Garados" },
                new Pokemon { Id = 131, LabelEn = "Lapras", LabelFr = "Lokhlass", LabelDe = "Lapras" },
                new Pokemon { Id = 132, LabelEn = "Ditto", LabelFr = "Métamorph", LabelDe = "Ditto" },
                new Pokemon { Id = 133, LabelEn = "Eevee", LabelFr = "Évoli", LabelDe = "Evoli" },
                new Pokemon { Id = 134, LabelEn = "Vaporeon", LabelFr = "Aquali", LabelDe = "Aquana" },
                new Pokemon { Id = 135, LabelEn = "Jolteon", LabelFr = "Voltali", LabelDe = "Blitza" },
                new Pokemon { Id = 136, LabelEn = "Flareon", LabelFr = "Pyroli", LabelDe = "Flamara" },
                new Pokemon { Id = 137, LabelEn = "Porygon", LabelFr = "Porygon", LabelDe = "Porygon" },
                new Pokemon { Id = 138, LabelEn = "Omanyte", LabelFr = "Amonita", LabelDe = "Amonitas" },
                new Pokemon { Id = 139, LabelEn = "Omastar", LabelFr = "Amonistar", LabelDe = "Amoroso" },
                new Pokemon { Id = 140, LabelEn = "Kabuto", LabelFr = "Kabuto", LabelDe = "Kabuto" },
                new Pokemon { Id = 141, LabelEn = "Kabutops", LabelFr = "Kabutops", LabelDe = "Kabutops" },
                new Pokemon { Id = 142, LabelEn = "Aerodactyl", LabelFr = "Ptéra", LabelDe = "Aerodactyl" },
                new Pokemon { Id = 143, LabelEn = "Snorlax", LabelFr = "Ronflex", LabelDe = "Relaxo" },
                new Pokemon { Id = 144, LabelEn = "Articuno", LabelFr = "Artikodin", LabelDe = "Arktos" },
                new Pokemon { Id = 145, LabelEn = "Zapdos", LabelFr = "Électhor", LabelDe = "Zapdos" },
                new Pokemon { Id = 146, LabelEn = "Moltres", LabelFr = "Sulfura", LabelDe = "Lavados" },
                new Pokemon { Id = 147, LabelEn = "Dratini", LabelFr = "Minidraco", LabelDe = "Dratini" },
                new Pokemon { Id = 148, LabelEn = "Dragonair", LabelFr = "Draco", LabelDe = "Dragonir" },
                new Pokemon { Id = 149, LabelEn = "Dragonite", LabelFr = "Dracolosse", LabelDe = "Dragoran" },
                new Pokemon { Id = 150, LabelEn = "Mewtwo", LabelFr = "Mewtwo", LabelDe = "Mewtu" },
                new Pokemon { Id = 151, LabelEn = "Mew", LabelFr = "Mew", LabelDe = "Mew" });

            context.SaveChanges();
        }
    }
}
